const DEFAULT_ERROR_STATE = {
  title: 'Fehler',
  message: 'Ein unbekannter Fehler ist aufgetreten.',
  technicalCode: 'UNKNOWN_ERROR',
  allowedAction: 'Support kontaktieren',
  retry: false,
  logging: { level: 'error', event: 'gui_error_unknown' },
};

export const ERROR_STATE_CATALOG = {
  API_UNREACHABLE: {
    title: 'Backend nicht erreichbar',
    message: 'Das Backend ist nicht erreichbar. Es wurden keine Daten geladen.',
    technicalCode: 'API_UNREACHABLE',
    allowedAction: 'Erneut versuchen',
    retry: true,
    logging: { level: 'warn', event: 'gui_api_unreachable' },
  },
  AUTH_REQUIRED: {
    title: 'Login erforderlich',
    message: 'Die Sitzung ist abgelaufen oder es fehlt eine Anmeldung.',
    technicalCode: 'AUTH_REQUIRED',
    allowedAction: 'Zur Anmeldung wechseln',
    retry: false,
    logging: { level: 'info', event: 'gui_auth_required' },
  },
  AUTH_SESSION_EXPIRED: {
    title: 'Login erforderlich',
    message: 'Die Sitzung ist abgelaufen oder es fehlt eine Anmeldung.',
    technicalCode: 'AUTH_REQUIRED',
    allowedAction: 'Zur Anmeldung wechseln',
    retry: false,
    logging: { level: 'info', event: 'gui_auth_required' },
  },
  UNAUTHORIZED: {
    title: 'Login erforderlich',
    message: 'Die Sitzung ist abgelaufen oder es fehlt eine Anmeldung.',
    technicalCode: 'AUTH_REQUIRED',
    allowedAction: 'Zur Anmeldung wechseln',
    retry: false,
    logging: { level: 'info', event: 'gui_auth_required' },
  },
  FORBIDDEN: {
    title: 'Zugriff verboten',
    message: 'Der aktuelle Benutzer darf diese Aktion oder Ansicht nicht ausfuehren.',
    technicalCode: 'FORBIDDEN',
    allowedAction: 'Berechtigung pruefen',
    retry: false,
    logging: { level: 'warn', event: 'gui_forbidden' },
  },
  AUTH_FORBIDDEN: {
    title: 'Zugriff verboten',
    message: 'Der aktuelle Benutzer darf diese Aktion oder Ansicht nicht ausfuehren.',
    technicalCode: 'FORBIDDEN',
    allowedAction: 'Berechtigung pruefen',
    retry: false,
    logging: { level: 'warn', event: 'gui_forbidden' },
  },
  ADMIN_REQUIRED: {
    title: 'Zugriff verboten',
    message: 'Fuer diese Ansicht sind Admin-Rechte erforderlich.',
    technicalCode: 'FORBIDDEN',
    allowedAction: 'Berechtigung pruefen',
    retry: false,
    logging: { level: 'warn', event: 'gui_forbidden' },
  },
  WORKSPACE_NOT_CONFIGURED: {
    title: 'Workspace fehlt',
    message: 'Es ist kein validierter Workspace fuer diese Sitzung konfiguriert.',
    technicalCode: 'WORKSPACE_NOT_CONFIGURED',
    allowedAction: 'Workspace-Konfiguration pruefen',
    retry: false,
    logging: { level: 'warn', event: 'gui_workspace_missing' },
  },
  AUTH_WORKSPACE_MISSING: {
    title: 'Workspace fehlt',
    message: 'Es ist kein validierter Workspace fuer diese Sitzung konfiguriert.',
    technicalCode: 'WORKSPACE_NOT_CONFIGURED',
    allowedAction: 'Workspace-Konfiguration pruefen',
    retry: false,
    logging: { level: 'warn', event: 'gui_workspace_missing' },
  },
  AUTH_WORKSPACE_NOT_ALLOWED: {
    title: 'Workspace fehlt',
    message: 'Der aktive Workspace ist fuer diese Sitzung nicht erlaubt.',
    technicalCode: 'WORKSPACE_NOT_CONFIGURED',
    allowedAction: 'Workspace-Konfiguration pruefen',
    retry: false,
    logging: { level: 'warn', event: 'gui_workspace_missing' },
  },
  WORKSPACE_ACCESS_FORBIDDEN: {
    title: 'Workspace fehlt',
    message: 'Der aktive Workspace ist fuer diese Sitzung nicht erlaubt.',
    technicalCode: 'WORKSPACE_NOT_CONFIGURED',
    allowedAction: 'Workspace-Konfiguration pruefen',
    retry: false,
    logging: { level: 'warn', event: 'gui_workspace_missing' },
  },
  TIMEOUT: {
    title: 'Zeitueberschreitung',
    message: 'Die Anfrage hat zu lange gedauert. Es wurden keine Daten geladen.',
    technicalCode: 'TIMEOUT',
    allowedAction: 'Erneut versuchen',
    retry: true,
    logging: { level: 'warn', event: 'gui_api_timeout' },
  },
  JOB_TIMEOUT: {
    title: 'Zeitueberschreitung',
    message: 'Die Anfrage hat zu lange gedauert. Es wurden keine Daten geladen.',
    technicalCode: 'TIMEOUT',
    allowedAction: 'Erneut versuchen',
    retry: true,
    logging: { level: 'warn', event: 'gui_api_timeout' },
  },
  VALIDATION_ERROR: {
    title: 'Validierungsfehler',
    message: 'Die Eingabe ist ungueltig oder unvollstaendig.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Eingabe korrigieren',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  AUTH_INVALID: {
    title: 'Validierungsfehler',
    message: 'Die Eingabe ist ungueltig oder unvollstaendig.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Eingabe korrigieren',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  FILE_REQUIRED: {
    title: 'Validierungsfehler',
    message: 'Die Eingabe ist ungueltig oder unvollstaendig.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Datei auswaehlen',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  INVALID_QUERY: {
    title: 'Validierungsfehler',
    message: 'Die Suchanfrage ist ungueltig.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Eingabe korrigieren',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  INVALID_PAGINATION: {
    title: 'Validierungsfehler',
    message: 'Die Anfrageparameter sind ungueltig.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Eingabe korrigieren',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  CHAT_MESSAGE_INVALID: {
    title: 'Validierungsfehler',
    message: 'Die Chat-Frage ist ungueltig.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Eingabe korrigieren',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  QUERY_REQUIRED: {
    title: 'Validierungsfehler',
    message: 'Eine Suchanfrage ist erforderlich.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Eingabe korrigieren',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  INSUFFICIENT_CONTEXT: {
    title: 'Validierungsfehler',
    message: 'Fuer diese Frage ist nicht genug Workspace-Kontext vorhanden.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Frage praezisieren oder Dokumente pruefen',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  FILE_TOO_LARGE: {
    title: 'Validierungsfehler',
    message: 'Die Datei ist groesser als die erlaubte Upload-Grenze.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Kleinere Datei auswaehlen',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  UNSUPPORTED_FILE_TYPE: {
    title: 'Validierungsfehler',
    message: 'Dieser Dateityp wird nicht unterstuetzt.',
    technicalCode: 'VALIDATION_ERROR',
    allowedAction: 'Unterstuetzten Dateityp auswaehlen',
    retry: false,
    logging: { level: 'info', event: 'gui_validation_error' },
  },
  SERVER_ERROR: {
    title: 'Serverfehler',
    message: 'Die Anfrage ist serverseitig fehlgeschlagen. Es wurden keine Daten geladen.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Spaeter erneut versuchen',
    retry: true,
    logging: { level: 'error', event: 'gui_server_error' },
  },
  RETRIEVAL_FAILED: {
    title: 'Serverfehler',
    message: 'Die Retrieval-Anfrage ist fehlgeschlagen.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Spaeter erneut versuchen',
    retry: true,
    logging: { level: 'error', event: 'gui_server_error' },
  },
  LLM_UNAVAILABLE: {
    title: 'Serverfehler',
    message: 'Der LLM-Dienst ist aktuell nicht verfuegbar.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Spaeter erneut versuchen',
    retry: true,
    logging: { level: 'error', event: 'gui_server_error' },
  },
  DOCUMENT_NOT_FOUND: {
    title: 'Serverfehler',
    message: 'Das Dokument wurde nicht gefunden.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Zur Dokumentliste wechseln',
    retry: false,
    logging: { level: 'warn', event: 'gui_server_error' },
  },
  CHAT_SESSION_NOT_FOUND: {
    title: 'Serverfehler',
    message: 'Die Chat-Sitzung wurde nicht gefunden.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Neue Chat-Sitzung oeffnen',
    retry: false,
    logging: { level: 'warn', event: 'gui_server_error' },
  },
  DOCUMENT_STATE_CONFLICT: {
    title: 'Serverfehler',
    message: 'Der Dokumentstatus erlaubt diese Aktion nicht.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Dokumentstatus aktualisieren',
    retry: false,
    logging: { level: 'warn', event: 'gui_server_error' },
  },
  INVALID_LIFECYCLE_TRANSITION: {
    title: 'Serverfehler',
    message: 'Dieser Dokumentstatus-Wechsel ist nicht erlaubt.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Dokumentstatus aktualisieren',
    retry: false,
    logging: { level: 'warn', event: 'gui_server_error' },
  },
  DOCUMENT_ALREADY_ARCHIVED: {
    title: 'Serverfehler',
    message: 'Das Dokument ist bereits archiviert.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Dokumentstatus aktualisieren',
    retry: false,
    logging: { level: 'warn', event: 'gui_server_error' },
  },
  DOCUMENT_ALREADY_DELETED: {
    title: 'Serverfehler',
    message: 'Das Dokument ist bereits geloescht.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Dokumentstatus aktualisieren',
    retry: false,
    logging: { level: 'warn', event: 'gui_server_error' },
  },
  SERVICE_UNAVAILABLE: {
    title: 'Serverfehler',
    message: 'Der Dienst ist aktuell nicht verfuegbar.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Spaeter erneut versuchen',
    retry: true,
    logging: { level: 'error', event: 'gui_server_error' },
  },
  DIAGNOSTICS_FAILED: {
    title: 'Serverfehler',
    message: 'Die Diagnose konnte nicht geladen werden.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Spaeter erneut versuchen',
    retry: true,
    logging: { level: 'error', event: 'gui_server_error' },
  },
  UI_RENDER_FAILED: {
    title: 'Serverfehler',
    message: 'Die Anfrage ist serverseitig fehlgeschlagen. Es wurden keine Daten geladen.',
    technicalCode: 'SERVER_ERROR',
    allowedAction: 'Support kontaktieren',
    retry: false,
    logging: { level: 'error', event: 'gui_server_error' },
  },
  IMPORT_FAILED: {
    title: 'Import fehlgeschlagen',
    message: 'Der Import konnte nicht abgeschlossen werden.',
    technicalCode: 'IMPORT_FAILED',
    allowedAction: 'Datei pruefen und erneut importieren',
    retry: false,
    logging: { level: 'error', event: 'gui_import_failed' },
  },
  PARSER_FAILED: {
    title: 'Import fehlgeschlagen',
    message: 'Die Datei konnte nicht verarbeitet werden.',
    technicalCode: 'IMPORT_FAILED',
    allowedAction: 'Datei pruefen und erneut importieren',
    retry: false,
    logging: { level: 'error', event: 'gui_import_failed' },
  },
  OCR_REQUIRED: {
    title: 'OCR erforderlich',
    message: 'Dieses Dokument benoetigt OCR, aber OCR ist nicht verfuegbar.',
    technicalCode: 'OCR_REQUIRED',
    allowedAction: 'OCR konfigurieren oder Textdatei importieren',
    retry: false,
    logging: { level: 'warn', event: 'gui_ocr_required' },
  },
  DUPLICATE_DOCUMENT: {
    title: 'Duplicate erkannt',
    message: 'Dieses Dokument ist bereits im Workspace vorhanden.',
    technicalCode: 'DUPLICATE_DOCUMENT',
    allowedAction: 'Vorhandenes Dokument oeffnen',
    retry: false,
    logging: { level: 'info', event: 'gui_duplicate_detected' },
  },
  DUPLICATE_DETECTED: {
    title: 'Duplicate erkannt',
    message: 'Dieses Dokument ist bereits im Workspace vorhanden.',
    technicalCode: 'DUPLICATE_DOCUMENT',
    allowedAction: 'Vorhandenes Dokument oeffnen',
    retry: false,
    logging: { level: 'info', event: 'gui_duplicate_detected' },
  },
};

export function getErrorState(code) {
  return ERROR_STATE_CATALOG[code] || DEFAULT_ERROR_STATE;
}

export function mapErrorToCatalog(error) {
  const visibleCode = error?.details?.backendCode || error?.code || 'UNKNOWN_ERROR';
  const classification = error?.details?.classification || error?.code || 'UNKNOWN_ERROR';
  const catalog = getErrorState(visibleCode);
  const classifiedCatalog = catalog === DEFAULT_ERROR_STATE ? getErrorState(classification) : catalog;
  const backendMessage = error?.message || error?.details?.backendMessage || null;

  return {
    ...classifiedCatalog,
    code: visibleCode,
    classification,
    message: classifiedCatalog.message,
    details: {
      ...(error?.details || {}),
      ...(backendMessage ? { backendMessage } : {}),
    },
    status: error?.status ?? null,
  };
}

export function mapDuplicateImportState({ fileName = '', documentId = null } = {}) {
  const catalog = getErrorState('DUPLICATE_DETECTED');
  return {
    ...catalog,
    code: 'DUPLICATE_DOCUMENT',
    classification: 'DUPLICATE_DOCUMENT',
    message: fileName
      ? `${fileName} ist bereits vorhanden. Es wurde kein neues Dokument angelegt.`
      : catalog.message,
    details: { documentId },
    status: null,
  };
}
